apiVersion: v1
kind: Pod
metadata:
  name: pod-test-configmap
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "echo $(SPECIAL_USER_KEY) is $(SPECIAL_ROLE_KEY)" ]
      env:
        - name: SPECIAL_USER_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.user
        - name: SPECIAL_ROLE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.role
      envFrom:
        - configMapRef:
            name: env-config
  restartPolicy: Never
